Broken Bond Module
rmrresearch/GhostFragment pull request #31
Opened 2023-06-09 19:27 UTC by wthayes

On my end, it is showing that there are many more commits than actually exist, but it only shows one file changing. Hopefully this pull request should still work.

2023-06-13 21:04 UTC, ryanmrichard requested changes

2023-06-13 21:04 UTC, ryanmrichard commented on src/ghostfragment/connectivity/hydrocarbon_fragment.hpp
Is this function unit tested somewhere? Also this file should be in `tests` not `src`.

2023-06-13 21:04 UTC, ryanmrichard commented on tests/cxx/unit_tests/ghostfragment/testing/broken_bonds.hpp
> +    set2.insert(bond_type(0, 1));
Shouldn't this bond be `(1,0)`? The order matters since the convention is the first index is in the fragment, the second is not.

2023-06-13 21:04 UTC, ryanmrichard commented on tests/cxx/unit_tests/ghostfragment/testing/broken_bonds.hpp
> +    set2.insert(bond_type(0, 1));
```suggestion
    set2.insert(bond_type(1, 0));
```

2023-06-13 21:04 UTC, ryanmrichard commented on tests/cxx/unit_tests/ghostfragment/testing/broken_bonds.hpp
> +    set3.insert(bond_type(1, 2));
```suggestion
    set3.insert(bond_type(2, 1));
```

2023-06-13 21:04 UTC, ryanmrichard commented on tests/cxx/unit_tests/ghostfragment/testing/broken_bonds.hpp
> +    set2.insert(bond_type(0, 1));
```suggestion
    set2.insert(bond_type(1, 0));
```

2023-06-14 13:59 UTC, wthayes commented on src/ghostfragment/connectivity/hydrocarbon/hydrocarbon.cpp
I thought that me putting in test was a mistake with no dire consequences, so I started putting things in src because I thought that is where they would end up. I can move it all back to test. My bad.

2023-06-14 14:09 UTC, ryanmrichard commented on src/ghostfragment/connectivity/hydrocarbon/hydrocarbon.cpp
the hydrocarbon functionality is really just for testing, which is why I advocate for putting it in `tests` because end users won't want to do extensive research on idealized hydrocarbons. `include` and `src` are respectively for the public-facing API and implementation of the generally applicable functionality.

2023-06-14 14:10 UTC, wthayes commented on src/ghostfragment/connectivity/hydrocarbon/hydrocarbon.cpp
Sounds good. Working on it now

2023-06-14 14:56 UTC, ryanmrichard approved these changes

2023-06-14 14:56 UTC, merged